chore(qa): Improve k8s reset debugging
uc-cdis/cloud-automation pull request #1410
Opened 2020-09-24 15:32 UTC by themarcelor

That should help us speed up the debugging in case any of our pods don't come up successfully.

2020-09-24 15:51 UTC, frickjack requested changes

2020-09-24 15:51 UTC, frickjack commented on gen3/bin/kube-wait4-pods.sh
> +          save_logs_from_failed_pods
Don't put this here - `kube-wait4-pods` gets called other places besides reset

2020-09-24 15:51 UTC, frickjack commented on gen3/lib/utils.sh
> +  # image pull errors
use local variables in functions

2020-09-24 15:51 UTC, frickjack commented on gen3/lib/utils.sh
> +save_logs_from_failed_pods() {
expose this as a cli method - something like this:
```
gen3 save-failed-pod-logs folderName
```
, then from the Jenkins pipeline - call out to that method if `gen3 reset` has a failed exit code

2020-09-24 17:37 UTC, themarcelor commented
Abandoned. Can't dedicate too much time for this right now.

2021-04-02 15:15 UTC, themarcelor commented
Re-opening this as this should help us debug several issues.

2021-04-02 15:19 UTC, fasi-md approved these changes

2021-04-12 20:50 UTC, m0nhawk approved these changes

2021-04-12 21:04 UTC, merged